name: bump-version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Select the bump type'
        type: choice
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'
          - 'premajor'
          - 'preminor'
          - 'prepatch'
          - 'prerelease'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: Bump verison
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3



      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: update version in package.json
        id: bump_version
        run: |
          VERSION=$(npm version ${{ github.event.inputs.bump }} --no-git-tag-version) >> $GITHUB_OUTPUT

      - name: update version in changelog.md
        run: |
          sed -i "s/## \[Unreleased\]/## \[Unreleased\]\n\n\n## [${{ steps.bump_version.outputs.VERSION }}] - $(date +%Y-%m-%d)/" CHANGELOG.md

      - name: create relase branch
        run: |
          git checkout -b release/${{ steps.bump_version.outputs.VERSION }}
          git push origin release/${{ steps.bump_version.outputs.VERSION }}

      - name: commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git add .

      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'bump version to ${{ steps.bump_version.outputs.VERSION }}'
          title: 'bump version to ${{ steps.bump_version.outputs.VERSION }}'
          body: 'bump version to ${{ steps.bump_version.outputs.VERSION }}'
          branch: release/${{ steps.bump_version.outputs.VERSION }}
          base: main
          labels: |
            release
